const hosts = [
  {
    _id: "5b21ca3eeb7f6fbccd471816",
    host_name: "g-pc",
    user: "User1",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Sadin",
    region: "NA",
    rating: "1",
    note: "tll",
  },
  {
    _id: "5b21ca3eeb7f6fbccd471817",
    host_name: "Home-pc",
    user: "PPC",
    status: "Offline",
    lastCheckIn: "",
    assigned_to: "Sadin",
    region: "NA",
    rating: "2",
    note: "tll",
  },
  {
    _id: "5b21ca3eeb7f6fbccd471819",
    host_name: "public-pc",
    user: "c12",
    status: "Offline",
    lastCheckIn: "",
    assigned_to: "Sadin",
    region: "NA",
    rating: "3",
    note: "thll",
  },
  {
    _id: "5b21ca3dfdfdfdf471819",
    host_name: "personal-pc",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "thill",
  },
  {
    _id: "5b21ca3fdfdf471819",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "thll",
  },
  {
    _id: "5b21cdfdf471819",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "thill",
  },
  {
    _id: "5b21ca3fdfdf4719",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "th sell",
  },
  {
    _id: "5b21ca3fdfdf41819",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "thil",
  },
  {
    _id: "b21ca3fdfdf471819",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "thisl",
  },
  {
    _id: "5b21ca3fdf19",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "this",
  },
  {
    _id: "5b21sssf471819",
    host_name: "p",
    user: "myselft",
    status: "Online",
    lastCheckIn: "",
    assigned_to: "Ali",
    region: "SA",
    rating: "3",
    note: "this",
  },
];

export function getHosts() {
  return hosts;
}

export function getHost(id) {
  return hosts.find((h) => h._id === id);
}
